apiVersion: v1
kind: Service
metadata:
  name: {{ include "qod.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qod.labels" . | nindent 4 }}
  {{- with .Values.service.rest.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.rest.type }}
  selector:
    {{- include "qod.selectorLabels" . | nindent 4 }}
  ports:
    - name: rest-ui
      port: {{ .Values.service.rest.port }}
      targetPort: rest-ui
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qod.fullname" . }}-flightsql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qod.labels" . | nindent 4 }}
    app.kubernetes.io/component: flightsql
  {{- with .Values.service.flightsql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.flightsql.type }}
  selector:
    {{- include "qod.selectorLabels" . | nindent 4 }}
  ports:
    - name: flightsql
      port: {{ .Values.service.flightsql.port }}
      targetPort: flightsql
      protocol: TCP
      {{- if and (eq .Values.service.flightsql.type "NodePort") .Values.service.flightsql.nodePort }}
      nodePort: {{ .Values.service.flightsql.nodePort }}
      {{- end }}
{{- if .Values.quack.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qod.fullname" . }}-quack
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qod.labels" . | nindent 4 }}
    app.kubernetes.io/component: quack
  {{- with .Values.service.quack.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.quack.type }}
  selector:
    {{- include "qod.selectorLabels" . | nindent 4 }}
  ports:
    - name: quack
      port: {{ .Values.service.quack.port }}
      targetPort: quack
      protocol: TCP
      {{- if and (eq .Values.service.quack.type "NodePort") .Values.service.quack.nodePort }}
      nodePort: {{ .Values.service.quack.nodePort }}
      {{- end }}
{{- end }}
{{- if .Values.rest.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qod.fullname" . }}-rest
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qod.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest-data
  {{- with .Values.service.restData.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.restData.type }}
  selector:
    {{- include "qod.selectorLabels" . | nindent 4 }}
  ports:
    - name: rest-data
      port: {{ .Values.service.restData.port }}
      targetPort: rest-data
      protocol: TCP
      {{- if and (eq .Values.service.restData.type "NodePort") .Values.service.restData.nodePort }}
      nodePort: {{ .Values.service.restData.nodePort }}
      {{- end }}
{{- end }}
