export QOD_RUNTIME_TYPE=fleet QOD_FLEET_JOIN_TOKEN=dev-join-token QOD_API_KEY=dev-key
export QOD_FLEET_HEARTBEAT_SEC=2 QOD_FLEET_HEARTBEAT_TIMEOUT_SEC=6 QOD_FLEET_REASSIGN_AFTER_SEC=30 QOD_RECONCILE_INTERVAL_SEC=5
QOD_VERSION=BUILD ./scripts/run-jar.sh
